name: mysql
version: 0.1.0
description: Chart for MySQL
keywords:
- mysql
- database
- sql
home: https://www.mysql.com/
sources:
- https://github.com/kubernetes/charts
maintainers:
- name: Vic Iglesias
  email: viglesias@google.com
engine: gotpl
