apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-orca
  labels:
    app: spin
    stack: orca
spec:
  ports:
    - port: 8083
  selector:
    load-balancer-spin-orca: "true"
