apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-rosco
  labels:
    app: spin
    stack: rosco
spec:
  ports:
    - port: 8087
  selector:
    load-balancer-spin-rosco: "true"
