steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  args: ['-c', 'build -t gcr.io/vic-goog/jenkins-master:`echo 3.2.1` stable/jenkins/master-image && gcr.io/vic-goog/jenkins-master:`echo 3.2.1`']
