steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  args: ['-c', 'VERSION=`echo 3.2.1` build -t gcr.io/vic-goog/jenkins-master:$VERSION stable/jenkins/master-image && gcr.io/vic-goog/jenkins-master:$VERSION']
