steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  args: ['-xe', '-c',
         'docker build -t gcr.io/vic-goog/jenkins-master:`cat stable/jenkins/master-image/VERSION` stable/jenkins/master-image && docker push gcr.io/vic-goog/jenkins-master:`cat stable/jenkins/master-image/VERSION`']
