{{ if .Values.gcs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spinnaker.fullname" . }}-gcs
  labels:
    app: {{ template "spinnaker.fullname" . }}
    component: halyard
type: Opaque
data:
  key.json: {{ .Values.gcs.jsonKey | b64enc }}
{{ end }}