# Images for each component
image:
  clouddriver: quay.io/spinnaker/clouddriver:v2.941.0
  pullPolicy: IfNotPresent

# Bucket to use when storing config data
storageBucket: spinnaker

# Resources to provide to each of
# the Spinnaker components
resources:
  limits:
    cpu: 1000m
    memory: 1280Mi
  requests:
    cpu: 1000m
    memory: 1280Mi

# Define which registries and repositories you want available in your
# Spinnaker pipeline definitions
accounts:
- name: dockerhub
  address: https://index.docker.io
  repositories:
    - library/alpine
    - library/ubuntu
    - library/centos
    - library/nginx

# Settings for notifications via email
mail:
  enabled: false
  host: smtp.example.org
  username: admin
  password: admin
  fromAddress: spinnaker@example.org
  port: 25

# Redis password to use for the in-cluster redis service
# Redis is not exposed publically
redis:
  redisPassword: password

# Minio access/secret keys for the in-cluster S3 usage
# Minio is not exposed publically
minio:
  AccessKey: spinnakeradmin
  SecretKey: spinnakeradmin

# Configuration for the Jenkins instance that is attached to the
# igor component of Spinnaker
jenkins:
  Master:
    Name: jenkins-master
    Image: "gcr.io/kubernetes-charts-ci/jenkins-master-k8s"
    ImageTag: "v0.6.0"
    ImagePullPolicy: "Always"
    Component: "jenkins-master"
    Cpu: "500m"
    Memory: "512Mi"
    ServicePort: 8080
    ServiceType: ClusterIP
    ContainerPort: 8080
    SlaveListenerPort: 50000
  
  Agent:
    Image: viglesiasce/spinnaker-jenkins-agent
    ImageTag: v0.2.0
    Cpu: "500m"
    Memory: "512Mi"
