server:
  port: ${services.gate.port:8084}
  address: 0.0.0.0
  # ssl:
  #   enabled: true
  #   keyStore: /opt/spinnaker/gate-tls/keystore.jks
  #   keyStorePassword: a1pine
  #   keyAlias: server

# Circular references since we're already using 'services'
# services:
#   clouddriver:
#     baseUrl: ${services.clouddriver.baseUrl:localhost:7002}
#   orca:
#     baseUrl: ${services.orca.baseUrl:localhost:8083}
#   front50:
#     baseUrl: ${services.front50.baseUrl:localhost:8080}
# #optional services:
#   echo:
#     enabled: ${services.echo.enabled:true}
#     baseUrl: ${services.echo.baseUrl:8089}
#   flapjack:
#     enabled: ${services.flapjack.enabled:false}
#   igor:
#     enabled: ${services.igor.enabled:false}
#     baseUrl: ${services.igor.baseUrl:8088}

cors:
  allowedOriginsPattern: '^https?://(?:localhost|[^/]+\.example\.com)(?::[1-9]\d*)?/?$'

redis:
  connection: ${services.redis.connection}
