apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-kube-config
  labels:
    release: {{.Release.Name | quote}}
    app: {{template "fullname" .}}
    heritage: {{.Release.Service | quote}}
data:
  config: |
    apiVersion: v1
    kind: Config
    current-context: default-context
    clusters:
    - name: default
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes
    users:
    - name: default
      user:
        username: admin
        password: dIbwOIPRmY13iCc1
    contexts:
    - context:
        user: default
        cluster: default
        namespace: default
      name: default-context
