apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-default-kubeconfig
  labels:
    app: {{ template "fullname" . }}
    component: clouddriver
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: local
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes
    contexts:
    - name: default
      context:
        cluster: local
    name: default
    current-context: "default"
    preferences: {}
