apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-s3-config
  labels:
    release: {{.Release.Name | quote}}
    app: {{template "fullname" .}}
    heritage: {{.Release.Service | quote}}
data:
  credentials: |
    [default]
    aws_access_key_id={{ .Values.minio.AccessKey }}
    aws_secret_access_key={{ .Values.minio.SecretKey }}
