---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: {{ .Release.Name }}-halyard
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: edit
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ template "fullname" . }}-halyard
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: {{ template "fullname" . }}-halyard
 namespace: {{ .Release.Namespace }}