apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-orca
  labels:
    app: {{ template "fullname" . }}
    component: orca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: orca
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/configmap/spinnaker-config.yaml") . | sha256sum }}
    spec:
      containers:
        - image: {{ .Values.images.orca }}
          name: orca
          ports:
            - containerPort: 8083
              name: orca
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "fullname" . }}-spinnaker-config
          readinessProbe:
            httpGet:
              path: /env
              port: 8083
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: {{ template "fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "fullname" . }}-spinnaker-config
