apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-deck
  labels:
    app: spin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        replication-controller: spin-deck-v000
        load-balancer-spin-deck: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/deck:master
          name: deck
          command:
            - /bin/bash
            - -c
          args:
            - "cp /opt/spinnaker/config/settings.js .; npm start"
          env:
            - name: DECK_HOST
              value: "0.0.0.0"
            - name: DECK_PORT
              value: "9000"
          ports:
            - containerPort: 9000
              name: deck
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "fullname" . }}-spinnaker-config
      volumes:
        - name: {{ template "fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "fullname" . }}-spinnaker-config
