apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-orca
  labels:
    app: spin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        replication-controller: spin-orca-v000
        load-balancer-spin-orca: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/orca:master
          name: orca
          ports:
            - containerPort: 8083
              name: orca
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "fullname" . }}-spinnaker-config
          readinessProbe:
            httpGet:
              path: /env
              port: 8083
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: {{ template "fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "fullname" . }}-spinnaker-config
